### ISSUE TITLE
Automatically watermark the scaled images

### ISSUE THREAD

**Issue by ghost** [Feenders/miresize#2]
**Is your feature request related to a problem? Please describe.**

Automatically watermark the scaled images

**Describe the solution you'd like**

Automatically watermark the scaled images

**Describe alternatives you've considered**

 insert the watermark on the scaled images

**Comment by Feenders** [comment]
Watermarking will be available next version!

**Comment by RubbelDeCatc** [comment]
Watermarking should work if you change line 91 of images.php from $watermark=false to $watermark=true
Look https://github.com/Feenders/miresize/blob/master/library/images.php
Replace the file /media/images/watermark.png with your watermark overlay!

Happy new year!
