### ISSUE TITLE
Is miresize still in development or abandonware?

### ISSUE THREAD

**Issue by ghost** [Feenders/miresize#3]
Is miresize still in development or abandonware?

**Comment by Feenders** [comment]
Shure! Do you have a Issue?

**Comment by ghost** [comment]
Feature

What you need to do till version with images watermarking will be available?

**Comment by RubbelDeCatc** [comment]
Watermarking should work if you change line 91 of  images.php from $watermark=false to $watermark=true
Look  https://github.com/Feenders/miresize/blob/master/library/images.php 
Replace the file /media/images/watermark.png with your watermark overlay!

Happy new year!

**Comment by ghost** [comment]
thank you RubbelDeCatc

Feenders can you make new version release with images watermarking available it seems so simple?

Happy new year!
