### ISSUE TITLE
Why Version 1.0 With Watermarking miresize release not published here on github

### ISSUE THREAD

**Issue by ghost** [Feenders/miresize#6]
Why Version 1.0 With Watermarking miresize release not published here on github?

Is it a secret or Feenders closed this question without answering by mistake?

**Comment by Feenders** [comment]
Please use your BRAIN!
This is a Joomla plugin. You can use our website, the JED, or just ZIP the git repo and install it to your joomla installation.

btw: your behavior is childish and annoying

**Comment by ghost** [comment]
strange why no answer provided why Feenders dont want 1.0 With Watermarking miresize release to be published here on github

Feenders it is annoying and strange why miresize release not published here on github
